### ISSUE TITLE
crashes node red on file selection

### ISSUE THREAD

**Issue by vikingsraven** [st-one-io/node-red-contrib-ui-media#26]

**Comment by vikingsraven** [comment]
NPM v7.19.1
Node 14.17.6
Node red 2.2.2
Crashes node red when trying to open a file. 

```
1 Apr 16:09:14 - [error] TypeError: path must be absolute or specify root to res.sendFile
    at ServerResponse.sendFile (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\node-red\node_modules\express\lib\response.js:430:11)
    at C:\Users\xxxxxx\.node-red\node_modules\node-red-contrib-ui-media\ui_media.js:288:17
    at FSReqCallback.oncomplete (fs.js:180:23)
```

**Comment by Elliot-Richardson** [comment]
I'm experiencing this exact issue, were you able to find a resolution? Looking into the .node-red file I can see the upload is successful and the image is in the appropriate ui-media folder but the path doesn't seem to allow me to update it to being absolute. Nor am I able to specify the root to use.

**Comment by Elliot-Richardson** [comment]
Hi,

I found that the issue was in line 288 of the ui-media.js file. When I checked the pathImage it was trying to send to res.sendFile because I am on a windows machine it was appending 'C:' to the front of the path:

![image](https://user-images.githubusercontent.com/103443350/187638422-d381fbae-0e03-4d29-bdac-1b7121a84b44.png)

If you comment out the highlighted line below that ought to resolve your problem:

![ui-media issue](https://user-images.githubusercontent.com/103443350/187638574-c4e4de08-bc55-45fb-a128-447e52ad0748.PNG)
